name: CI Pipeline
on: [push,workflow_dispatch, pull_request]

jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    env:
      APP_URL: ${{ secrets.APP_URL }}
      APP_USER: ${{ secrets.APP_USER }}
      APP_PASSWORD: ${{ secrets.APP_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Verify Java Installation
        run: java -version

      - name: Install Chrome and Driver
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: 'stable'

      - name: Run tests
        run: mvn clean test
# temporary change to test secrets in GitHub Actions
# temporary change to test secrets in GitHub Actions 2
